# SPDX-License-Identifier: Apache-2.0
"""Reject agent branding in Git commit messages."""

from __future__ import annotations

import re
import sys
from collections.abc import Sequence
from pathlib import Path

FORBIDDEN_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("Maestro", re.compile(r"\bmaestro\b", re.IGNORECASE)),
    ("Claude", re.compile(r"\bclaude\b", re.IGNORECASE)),
    ("Codex", re.compile(r"\bcodex\b", re.IGNORECASE)),
    ("Generated by", re.compile(r"\bgenerated(?:\s+|-)by\b", re.IGNORECASE)),
    ("Generated with", re.compile(r"\bgenerated(?:\s+|-)with\b", re.IGNORECASE)),
)


def committed_text(message: str) -> str:
    """Return message content after removing Git comment lines."""
    return "\n".join(line for line in message.splitlines() if not line.lstrip().startswith("#"))


def forbidden_labels(message: str) -> list[str]:
    """Return labels for all forbidden patterns found in the message."""
    text = committed_text(message)
    return [label for label, pattern in FORBIDDEN_PATTERNS if pattern.search(text)]


def main(argv: Sequence[str] | None = None) -> int:
    """Validate the commit message file passed as the first argument."""
    arguments = list(sys.argv[1:] if argv is None else argv)
    if len(arguments) != 1:
        print("Usage: check_commit_message.py <commit-message-file>", file=sys.stderr)
        return 2

    message_path = Path(arguments[0])
    try:
        message = message_path.read_text(encoding="utf-8", errors="replace")
    except OSError as error:
        print(f"Error: cannot read commit message file {message_path}: {error}", file=sys.stderr)
        return 2

    matches = forbidden_labels(message)
    if not matches:
        return 0

    print("Error: commit message contains forbidden agent branding:", file=sys.stderr)
    for label in matches:
        print(f"  - {label}", file=sys.stderr)
    print("Remove agent names, generated-by text, and AI co-author trailers.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
